### ISSUE TITLE
01Linx, lnx07 opdracht, hoeveel RAM ssh gebruikt

### ISSUE THREAD

**Issue by NederLANA** [techgrounds/cloud-6-repo-P03KI#4]
Een deels van de opdracht vraagt voor hoeveel Ram gebruikt de SSH. Ik zie het niet van jouwe screenshots

Ik gebruik
$ free -m

**Comment by P03KI** [comment]
Hoi,

In de status zie dat het SSH 1.3 M gebruikt.
free -m gaat over het totale werkgeheugen.
